select_cmode:
  description: Select Color mode of Epson projector
  fields:
    entity_id:
      description: Name of projector
      example: "media_player.epson_projector"
    cmode:
      description: Name of Cmode
      example: "cinema"

select_picture_memory:
  description: Select Picture memory of Epson projector
  fields:
    entity_id:
      description: Name of projector
      example: "media_player.epson_projector"
    memory_num:
      description: Which memory?
      example: "memory_1"

select_lens_memory:
  description: Select Lens memory of Epson projector
  fields:
    entity_id:
      description: Name of projector
      example: "media_player.epson_projector"
    lp_memory_num:
      description: Which lens memory?
      example: "memory_1"
